export const routes = {
  home: "Tổng quan",
  members: "Hội viên",
  trainers: "Huấn luyện viên",
  staff: "Nhân sự",
  packages: "Gói tập",
  assignments: "Phân công PT",
  schedule: "Lịch lớp & hẹn",
  billing: "Hóa đơn",
  revenue: "Doanh thu",
  checkin: "Check-in",
  equipment: "Thiết bị",
  reports: "Báo cáo",
  exercises: "Thư viện bài tập",
  notifications: "Thông báo",
  settings: "Tài khoản",
  clients: "Học viên",
  builder: "Giáo án",
  progress: "Tiến trình",
  workout: "Buổi tập",
  membership: "Gói tập & PT",
  nutrition: "Dinh dưỡng",
};

export const allowedPages = {
  ADMIN: [
    "home",
    "members",
    "trainers",
    "staff",
    "packages",
    "assignments",
    "schedule",
    "billing",
    "revenue",
    "checkin",
    "equipment",
    "reports",
    "exercises",
    "notifications",
    "settings",
  ],
  PT: [
    "home",
    "clients",
    "builder",
    "schedule",
    "progress",
    "notifications",
    "settings",
  ],
  MEMBER: [
    "home",
    "workout",
    "schedule",
    "progress",
    "membership",
    "nutrition",
    "checkin",
    "notifications",
    "settings",
  ],
};

export const mainPages = {
  ADMIN: ["home", "members", "schedule", "revenue"],
  PT: ["home", "clients", "builder", "schedule"],
  MEMBER: ["home", "workout", "schedule", "progress"],
};
