export const sessionSeed = [
  {
    id: "s1",
    time: "06:30",
    end: "07:20",
    name: "Yoga buổi sáng",
    type: "YOGA",
    coach: "Trần Mai Chi",
    room: "Phòng Yoga",
    filled: 14,
    capacity: 18,
    duration: 50,
  },
  {
    id: "s2",
    time: "09:00",
    end: "10:00",
    name: "Tập sức mạnh",
    type: "GYM",
    coach: "Lê Quốc Bảo",
    room: "Khu tạ tự do",
    filled: 8,
    capacity: 12,
    duration: 60,
  },
  {
    id: "s3",
    time: "17:30",
    end: "18:20",
    name: "Boxing căn bản",
    type: "BOXING",
    coach: "Phạm Đức Huy",
    room: "Phòng Boxing",
    filled: 10,
    capacity: 16,
    duration: 50,
  },
  {
    id: "s4",
    time: "19:00",
    end: "19:50",
    name: "Yoga thư giãn",
    type: "YOGA",
    coach: "Trần Mai Chi",
    room: "Phòng Yoga",
    filled: 12,
    capacity: 18,
    duration: 50,
  },
];
