export const exerciseSeed = [
  {
    id: "e1",
    name: "Goblet squat",
    group: "Chân",
    equipment: "Tạ đơn",
    sets: 3,
    reps: 12,
    weight: 12,
  },
  {
    id: "e2",
    name: "Romanian deadlift",
    group: "Đùi sau",
    equipment: "Tạ đơn",
    sets: 3,
    reps: 10,
    weight: 16,
  },
  {
    id: "e3",
    name: "Lat pulldown",
    group: "Lưng",
    equipment: "Máy kéo",
    sets: 3,
    reps: 12,
    weight: 25,
  },
  {
    id: "e4",
    name: "Dumbbell press",
    group: "Ngực",
    equipment: "Tạ đơn",
    sets: 3,
    reps: 10,
    weight: 8,
  },
  {
    id: "e5",
    name: "Plank",
    group: "Core",
    equipment: "Thảm",
    sets: 3,
    reps: 45,
    weight: 0,
    seconds: true,
  },
];
