CREATE TABLE IF NOT EXISTS email_verifications (
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 code_hash VARCHAR(100) NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 sent_at TIMESTAMPTZ NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0,
 window_start TIMESTAMPTZ NOT NULL,
 sends_window INTEGER NOT NULL DEFAULT 1
);
