CREATE TABLE IF NOT EXISTS staff (
 id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(255) NOT NULL DEFAULT '',
 phone VARCHAR(30) NOT NULL DEFAULT '', position VARCHAR(80) NOT NULL,
 status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE'))
);
